Configuration console command
bumble-tech/bumble-doc-gen pull request #54
Opened 2023-10-25 07:53 UTC by misantron

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Configuration console command to display config settings

## Issue ticket number and link

https://github.com/bumble-tech/bumble-doc-gen/issues/48

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have added/updated tests.

2023-10-26 07:55 UTC, misantron commented
@shcherbanich should configuration command support all configuration keys or just collections?

2023-10-26 08:29 UTC, shcherbanich commented
Ideally, this command should support the output of all keys

2023-10-31 11:05 UTC, seanmcn requested changes
Overall it looks good thank you! 

I've requested some minor changes around logging messages. 

I also think it would be nice if the command could output all configuration, as a user will be unlikely to iniitally know the config keys available. 

Finally, there are merge conflicts on the branch (due to the generated documentation), so please  merge `1.x.x` into the branch again & regenerate the documentation.

Thanks :)

2023-10-31 11:05 UTC, seanmcn commented on src/Core/Configuration/Configuration.php
>              throw new InvalidConfigurationParameterException(
Can you change `cache_dir` in the message here to `ConfigurationKey::CACHE_DIR`?

2023-11-20 11:32 UTC, seanmcn approved these changes

2023-11-20 11:33 UTC, merged

2023-11-20 11:33 UTC, seanmcn commented
@misantron thank you for your contribution!